stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  script:
    - deploy/unit_test.sh

build_app:
  stage: build
  cache:
    untracked: true
  script:
    - deploy/build_app.sh

build_docker_image:
  stage: build
  cache:
    untracked: true
  script:
    - deploy/build_docker_image.sh