cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy
  # - release # enable this if you intend to release to prod

unit_test:
  stage: test
  script:
    - deploy/unit_test.sh

build_app:
  stage: build
  script:
    - deploy/compile_app.sh
    - deploy/build_docker_image.sh

deploy_staging:
  stage: deploy
  script:
    - deploy/push_to_heroku.sh
  variables:
    CUSTOM_ENVIRONMENT: "staging-"

# deploy:
#   environment: production
#   stage: release
#   script:
#     - deploy/push_to_heroku.sh
